{% set version = "0.9.2" %}
{% set sha256 = "5d11a3bd5e55c64988163473c5066d76e6b5cd7bf51cbc0adfb36f894c80d937" %}
{% set build_number = 0 %}

package:
  name: "pdgstaging"
  version: {{ version }}

source:
  url: https://github.com/PermafrostDiscoveryGateway/viz-staging/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build_number }}

requirements:
  host:
    - python >=3.9,<4.0
    - pip
  run:
    - python >=3.9,<4.0
    - numpy >=1.2,<2.0
    - pandas >=1.4,<2.0
    - shapely >=2,<3.0
    - geopandas >=0.12.2,<1.0
    - morecantile >=3.1,<4.0
    - rtree >=0.9,<1.0
    - filelock >=3.6,<4.0
    - coloraide >=0.10,<1.0
    - colormaps ==0.4.0

    # HACK: block transitive dependency incompatibilities
    # See pending fix in upstream repo: https://github.com/PermafrostDiscoveryGateway/viz-staging/pull/51
    - pydantic <2.0
    - fiona <1.9

test:
  imports:
    - pdgstaging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PermafrostDiscoveryGateway/viz-staging
  license: Apache-2.0
  license_file: LICENSE
  summary: Polar Discovery Gateway visualization staging software

extra:
  recipe-maintainers:
    - mfisher87
    - rushirajnenuji
